##############################################
# +----------------------------------------+ #
# |            Item Update List            | #
# +----------------------------------------+ #
##############################################

update:
  "masterwork:masterwork_chestplate": "masterwork:masterwork_chestplate"
  "masterwork:masterwork_helmet": "masterwork:masterwork_helmet"

##############################################
# +----------------------------------------+ #
# |          Item configurations           | #
# +----------------------------------------+ #
##############################################

items:
  architects-wand:
    CraftStair:
      - direction
      - half
      - stair_shape
      - waterlogged
    CraftWall:
      - wall_height
      - center
      - waterlogged
    CraftFence:
      - connection
      - waterlogged
    CraftIronBars:
      - connection
    CraftStainedGlassPane:
      - connection
    CraftLever:
      - direction
      - attachment
      - powered
    CraftTripWireHook:
      - direction
      - attached
      - powered
    CraftBed:
      - direction
      - bed_part
    CraftBigDripleaf:
      - dripleaf_tilt
      - direction
    CraftButton:
      - direction
      - powered
    CraftTrapDoor:
      - open
    CraftDoor:
      - open
  creeper_bow:
    tnt_chance: 0.5
    offset: 1
    velocity_multiplier: 2.0
    fuse-time: 


##############################################
# +----------------------------------------+ #
# |                Language                | #
# +----------------------------------------+ #
##############################################

# This section has editable language configurations for plugin messages.

messages:
  tool-broken: "§c§lU§f§lL §7§lItems §8§l» §cThis tool is broken and needs repair to continue using it."
  armour-broken: "§c§lU§f§lL §7§lItems §8§l» §cThis armour is broken and you will take double damage until it is repaired."